# Generated by Django 5.2.2 on 2025-08-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_alter_pharmacy_open_hours'),
        ('Purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pharmacy',
            field=models.ForeignKey(default='178c0a84-1063-464a-adc9-0ccfe08c6a36', on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacy'),
            preserve_default=False,
        ),
    ]
