# Generated by Django 5.2.2 on 2025-08-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_supplier_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='expiry_date',
        ),
    ]
