# Generated by Django 5.2.2 on 2025-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(db_index=True, max_length=100)),
                ('dci1', models.CharField(max_length=100)),
                ('dosage1', models.CharField(blank=True, max_length=20, null=True)),
                ('unite_dosage1', models.CharField(blank=True, max_length=20, null=True)),
                ('forme', models.CharField(max_length=50)),
                ('presentation', models.CharField(max_length=200)),
                ('ppv', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prix_br', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('princeps_generique', models.CharField(choices=[('P', 'Princeps'), ('G', 'Générique')], max_length=1)),
                ('taux_remboursement', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
    ]
