# Generated by Django 5.2.1 on 2025-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_medicine_remise_medicine_tva_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dci1',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['nom'], name='medicine_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['code'], name='medicine_code_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['dci1'], name='medicine_dci1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['nom', 'code'], name='medicine_search_idx'),
        ),
    ]
