# Generated by Django 5.2.2 on 2025-07-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacyuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='pharmacyuser',
            table=None,
        ),
    ]
