# Generated by Django 5.2.2 on 2025-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_alter_pharmacyuser_options_alter_pharmacyuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyuser',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='can_manage_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='can_manage_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
