# Generated by Django 5.2.2 on 2025-07-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_update_pharmacist_permissions'),
        ('Authentification', '0005_update_pharmacist_permissions'),
    ]

    operations = [
    ]
