# Generated by Django 5.2.2 on 2025-06-29 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicine', '0002_medicine_remise_medicine_tva_medicine_type'),
        ('Pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3)),
                ('payment_type', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('dest_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_exchanges', to='Pharmacy.pharmacy')),
                ('source_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_exchanges', to='Pharmacy.pharmacy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Exchanges.exchange')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine')),
            ],
        ),
    ]
