# Generated by Django 5.2.2 on 2025-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
