# Generated by Django 5.2.2 on 2025-07-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_medicine_pharmacyinventory_sale_saleitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='pharmacyinventory',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='PharmacyInventory',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
