# Generated by Django 5.2.2 on 2025-06-29 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('quantity_changed', models.PositiveIntegerField()),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pharmacy_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='Pharmacy.pharmacymedicine')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
