# Generated by Django 5.2.2 on 2025-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_sale_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
