# Generated by Django 5.2.2 on 2025-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacymedicine',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
