# Generated by Django 5.2.2 on 2025-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_pharmacymedicine_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='open_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
